name: "Hello world workflow"

# Controls when the action will run. Triggers the workflow on push one to master or production branch.
on:
  push: 
    branches:
      - main
      - production

jobs:
 hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "Hello World"
