name: "Multi Event Pipeline / Workflow"
on:

   push: 
      branches: 
          - main
          - test


jobs: 
    on-push:
       runs-on: ubuntu-latest
       steps:
            - name: "Running on main push"
              run: echo "Running on main push" 

    