name: "Multi Event Pipeline / Workflow"
on:

   push: 
      branches: 
          - main
          - test

   pull_request: 
          branches: 
            - main
            - test
    
   workflow_dispatch: 


jobs: 
    on-push:
       runs-on: ubuntu-latest
       steps:
            - name: "Running on main/test push"
              run: echo "Running on main/test push"
    
    on-pull-request:
       runs-on: ubuntu-latest
       steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"

    