name: "Multi Event Pipeline / Workflow"
on:

   push:

   pull_request: 
          branches: 
            - main

   workflow_dispatch: 


jobs: 
    on-push:
       if: github.event_name == 'push'
       runs-on: ubuntu-latest
       steps:
            - name: "Running on main/test push"
              run: echo "Running on main/test push"
    
    on-pull-request:
       if: github.event_name == 'pull_request'
       runs-on: ubuntu-latest
       steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"

    on-pull-request-closed:
       if: github.event_name == 'pull_request' && github.event.action == 'closed'
       runs-on: ubuntu-latest
       steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"
    
    on-workflow-dispatch:
       if: github.event_name == 'workflow_dispatch'
       runs-on: ubuntu-latest
       steps:
            - name: "Running on workflow dispatch"
              run: echo "Running on workflow dispatch"

    